source "https://gitcafe.com/akuandev/Specs.git"
platform :ios, "7.0"

target "LYZSJC" do
    pod "AFNetworking"
    pod "MJRefresh"
    pod "SDWebImage"
    pod "SVProgressHUD"
    pod "MJExtension"
    pod "DACircularProgress"
end

